CREATE DATABASE cruise_spring;
use cruise_spring;
CREATE TABLE if not exists USERS (
ID SERIAL PRIMARY KEY,
USERNAME VARCHAR (30) NOT NULL,
PASSWORD VARCHAR (30) NOT NULL,
FIRST_NAME VARCHAR (30) NOT NULL,
SECOND_NAME VARCHAR (30) NOT NULL,
BALANCE FLOAT
);

CREATE TABLE if not exists SHIP (
ID SERIAL PRIMARY KEY,
NAME VARCHAR (30) NOT NULL,
PASSENGER_AMOUNT INTEGER NOT NULL,
ROUTE_TO VARCHAR(30) NOT NULL,
ROUTE_FROM VARCHAR(30) NOT NULL,
AMOUNT_PORTS INTEGER NOT NULL,
TRAVEL_START DATE,
TRAVEL_END DATE,
STANDART_PRICE FLOAT
);

CREATE TABLE if not exists CRUISE_INFO (
ID SERIAL PRIMARY KEY,
SHIP_ID INTEGER REFERENCES SHIP(ID),
ROOM_TYPE VARCHAR (30),
USER_ID INTEGER REFERENCES USER_ROLE(ID),
TOTAL_PRICE FLOAT
);

CREATE TABLE IF NOT EXISTS ROLES (
ID SERIAL PRIMARY KEY,
NAME VARCHAR (100)
);

CREATE TABLE IF NOT EXIST USER_ROLES(
USER_ID BIGINT REFERENCES USERS(ID),
ROLE_ID BIGINT REFERENCES ROLES(ID)
);